#!/usr/bin/env python3
"""Rebuild the standalone installer from runtime sources and existing setup template."""
from pathlib import Path
import re
root=Path(__file__).resolve().parents[2]
template=(root/'bundle.ps1').read_text()
header=re.search(r"\$header = @'\n(.*?)\n'@",template,re.S).group(1)
footer=re.search(r"\$footer = @'\n(.*?)\n'@",template,re.S).group(1)
chunks=[header.replace('Generated by bundle.ps1','Generated by derby/tools/bundle.py')+'\n']
for p in sorted(root.rglob('*')):
 if not p.is_file(): continue
 rel=p.relative_to(root).as_posix()
 if rel in ('install.lua','get.lua') or any(rel.startswith(pkg+'/'+x+'/') for pkg in ['derby','pineslots','pinejack','pinebox','casino','tables'] for x in ['tests','tools','docs']): continue
 if p.suffix!='.lua' and rel not in ['derby/vendor/LICENSE','derby/vendor/REVISION.txt','derby/odds.json']: continue
 text=re.sub(r'(?m)^[ \t]+$', '', p.read_text()); level=''
 while ']'+level+']' in text: level+='='
 chunks.append("writeFile('%s', [%s[\n%s]%s])\n"%(rel,level,text,level))
chunks.append(footer+'\n')
(root/'install.lua').write_text('\n'.join(chunks))
print('Bundled',len(chunks)-2,'runtime files')
# The single-game installer's manifest is regenerated alongside the bundle.
import runpy; runpy.run_path(str(root/'tools'/'manifest.py'))
