local H = require("helpers")
local send, find, count = H.send, H.find, H.count

return {
    { "keys go only to the focused window", function(T)
        H.withKernel(function(k)
            local p1, l1 = H.echo(k, { label = "one" })
            local p2, l2 = H.echo(k, { label = "two" })
            T.eq(k.focus, p2, "newest window is focused")
            send(k, "key", keys.a, false)
            T.ok(find(l2, "key"), "focused got key")
            T.ok(not find(l1, "key"), "unfocused did not get key")
        end)
    end },
    { "non-input events are broadcast", function(T)
        H.withKernel(function(k)
            local _, l1 = H.echo(k)
            local _, l2 = H.echo(k)
            send(k, "custom_thing", 42)
            T.eq((find(l1, "custom_thing") or {})[2], 42, "first")
            T.eq((find(l2, "custom_thing") or {})[2], 42, "second")
        end)
    end },
    { "mouse clicks are translated to window coordinates", function(T)
        H.withKernel(function(k)
            H.echo(k)
            local p2, l2 = H.echo(k)
            local c = k.frames[p2].client
            T.eq(c.x, 27, "right tile client x")
            T.eq(c.y, 2, "client below title")
            send(k, "mouse_click", 1, 30, 5)
            local ev = find(l2, "mouse_click")
            T.ok(ev, "click delivered")
            T.eq(ev[3], 4, "local x")
            T.eq(ev[4], 4, "local y")
        end)
    end },
    { "first click on an unfocused window only focuses it", function(T)
        H.withKernel(function(k)
            local p1, l1 = H.echo(k)
            H.echo(k)
            send(k, "mouse_click", 1, 5, 5)
            T.eq(k.focus, p1, "focus moved")
            T.ok(not find(l1, "mouse_click"), "activation click swallowed")
            send(k, "mouse_click", 1, 5, 5)
            T.ok(find(l1, "mouse_click"), "second click delivered")
        end)
    end },
    { "a fifth window iconizes the least recently focused", function(T)
        H.withKernel(function(k)
            local first = H.echo(k, { label = "a" })
            for _, l in ipairs({ "b", "c", "d", "e" }) do H.echo(k, { label = l }) end
            T.eq(#k:tiles(), 4, "four tiles")
            T.ok(first.iconic, "first window iconized")
            T.eq(k:icons()[1], first, "icon strip shows it")
        end)
    end },
    { "ctrl+tab cycles focus and is not delivered", function(T)
        H.withKernel(function(k)
            local p1, l1 = H.echo(k)
            local p2, l2 = H.echo(k)
            send(k, "key", keys.leftCtrl, false)
            send(k, "key", keys.tab, false)
            send(k, "key_up", keys.leftCtrl)
            T.eq(k.focus, p1, "focus cycled")
            T.ok(not find(l1, "key") or find(l1, "key")[2] ~= keys.tab, "tab swallowed")
            T.ok(not find(l2, "key") or find(l2, "key")[2] ~= keys.tab, "tab swallowed 2")
        end)
    end },
    { "os.reboot inside an app closes only that app", function(T)
        H.withKernel(function(k)
            local p1 = H.echo(k)
            local p2 = H.echo(k)
            k:deliver(p1, "do_reboot")
            send(k, "noop")
            T.ok(p1.dead, "caller closed")
            T.ok(not p2.dead, "other app alive")
            T.eq(#k.procs, 1, "one left")
            T.eq(k.focus, p2, "focus moved to survivor")
        end)
    end },
    { "terminate goes to the focused app", function(T)
        H.withKernel(function(k)
            local p1 = H.echo(k)
            local p2 = H.echo(k)
            send(k, "terminate")
            T.ok(p2.dead, "focused app ended")
            T.ok(not p1.dead, "other untouched")
        end)
    end },
    { "setMenus adds a menu bar and shrinks the client", function(T)
        H.withKernel(function(k)
            local menus = { { label = "File", items = { { id = "new", label = "New" }, "-", { id = "quit", label = "Exit" } } } }
            local p = H.echo(k, { menus = menus })
            local fr = k.frames[p]
            T.ok(fr.menu, "menu row present")
            local _, h = p.win.getSize()
            T.eq(h, 17 - 2, "client height")
        end)
    end },
    { "menu choices arrive as arcadeos_menu events", function(T)
        H.withKernel(function(k)
            local menus = { { label = "File", items = { { id = "new", label = "New" }, "-", { id = "quit", label = "Exit" } } } }
            local p, log = H.echo(k, { menus = menus })
            send(k, "mouse_click", 1, 3, 2)
            T.ok(k.menu, "dropdown open")
            send(k, "mouse_click", 1, 3, 5)
            T.ok(not k.menu, "dropdown closed")
            k:flushInboxes()
            local ev = find(log, "arcadeos_menu")
            T.ok(ev, "menu event delivered")
            T.eq(ev[2], "quit", "chose Exit")
        end)
    end },
    { "keyboard menu navigation", function(T)
        H.withKernel(function(k)
            local menus = { { label = "File", items = { { id = "new", label = "New" }, { id = "open", label = "Open" } } } }
            local p, log = H.echo(k, { menus = menus })
            send(k, "key", keys.leftCtrl, false)
            send(k, "key", keys.m, false)
            send(k, "key_up", keys.leftCtrl)
            T.ok(k.menu, "ctrl+m opened menu")
            send(k, "key", keys.down, false)
            send(k, "key", keys.enter, false)
            k:flushInboxes()
            T.eq((find(log, "arcadeos_menu") or {})[2], "open", "second item")
        end)
    end },
    { "system menu iconizes and the icon restores", function(T)
        H.withKernel(function(k)
            local p1 = H.echo(k, { label = "a" })
            local p2 = H.echo(k, { label = "b" })
            send(k, "mouse_click", 1, 28, 1)
            T.eq(k.menu and k.menu.kind, "system", "system menu open")
            local r = k.menu.rect
            send(k, "mouse_click", 1, r.x + 1, r.y + 1)
            T.ok(p2.iconic, "iconized")
            T.eq(#k:tiles(), 1, "one tile left")
            T.eq(k.frames[p1].title.w, 51, "remaining window takes full width")
            local slot = k.iconHits.slots[1]
            send(k, "mouse_click", 1, slot.x + 1, slot.y)
            T.ok(not p2.iconic, "restored")
            T.eq(k.focus, p2, "focused")
        end)
    end },
    { "zoom button takes the whole screen with chrome", function(T)
        H.withKernel(function(k)
            H.echo(k)
            local p = H.echo(k)
            local tr = k.frames[p].title
            send(k, "mouse_click", 1, tr.x + tr.w - 1, tr.y)
            T.ok(p.zoomed, "zoomed")
            T.eq(k.frames[p].title.w, 51, "full width title")
            T.eq(k.frames[p].client.h, 18, "client below title")
            send(k, "mouse_click", 1, 51, 1)
            T.ok(not p.zoomed, "unzoomed")
        end)
    end },
    { "zooming delivers term_resize to the app", function(T)
        H.withKernel(function(k)
            H.echo(k)
            local p, log = H.echo(k)
            local before = count(log, "term_resize")
            k:toggleZoom(p)
            H.pump(k, 0.1)
            T.eq(count(log, "term_resize"), before + 1, "resize delivered")
        end)
    end },
    { "fullscreen app gets the whole screen and palette is restored on switch", function(T)
        H.withKernel(function(k, parent)
            local p1 = H.echo(k, { label = "desk" })
            local p2 = H.echo(k, { display = "full", palette = { [colors.cyan] = 0x123456 } })
            local c = k.frames[p2].client
            T.eq(c.w * c.h, 51 * 19, "whole screen")
            T.ok(not H.paletteIsTheme(parent), "game palette active")
            send(k, "key", keys.leftCtrl, false)
            send(k, "key", keys.tab, false)
            send(k, "key_up", keys.leftCtrl)
            T.eq(k.focus, p1, "switched away")
            T.ok(p2.iconic, "game iconized")
            T.ok(H.paletteIsTheme(parent), "theme palette restored")
            local slot = k.iconHits.slots[1]
            send(k, "mouse_click", 1, slot.x + 1, slot.y)
            T.eq(k.focus, p2, "game back")
            T.ok(not H.paletteIsTheme(parent), "game palette back")
        end)
    end },
    { "close on a non-native app that ignores terminate kills it", function(T)
        H.withKernel(function(k)
            H.echo(k)
            local p = H.echo(k, { stubborn = true })
            k:close(p)
            k:reap()
            T.ok(p.dead, "killed")
        end)
    end },
    { "multishell compat launches windows and sets titles", function(T)
        H.withKernel(function(k)
            local p = H.echo(k)
            local id = k.compat.launch({ log = {} }, "/arcadeos/tests/fixtures/echo.lua")
            T.eq(#k.procs, 2, "launched")
            k.compat.setTitle(id, "Renamed")
            T.eq(k:byId(id).title, "Renamed", "title")
            T.eq(k.focus, p, "compat launch does not steal focus")
        end)
    end },
    { "kernel-modal box blocks input until dismissed", function(T)
        H.withKernel(function(k)
            local p, log = H.echo(k)
            local answer
            k:showModal("Test", "Hello", { "OK", "Cancel" }, function(i) answer = i end)
            send(k, "key", keys.a, false)
            T.ok(not find(log, "key"), "input held by modal")
            send(k, "key", keys.right, false)
            send(k, "key", keys.enter, false)
            T.eq(answer, 2, "cancel chosen")
            send(k, "key", keys.a, false)
            T.ok(find(log, "key"), "input flows again")
        end)
    end },
    { "small screens show one window at a time", function(T)
        H.withKernel({ w = 39, h = 13 }, function(k)
            local p1 = H.echo(k)
            local p2 = H.echo(k)
            T.ok(p1.iconic, "first iconized on turtle-sized screen")
            T.eq(k.frames[p2].title.w, 39, "full width")
        end)
    end },
}
