$outputFile = "install.lua"

$header = @'
-- Arcade OS Installer
-- Generated by bundle.ps1

local function ensureDirForPath(path)
    local dir = fs.getDir(path)
    if dir and dir ~= '' and not fs.exists(dir) then
        fs.makeDir(dir)
    end
end

local function writeFile(path, content)
    ensureDirForPath(path)
    local file = fs.open(path, 'w')
    file.write(content)
    file.close()
    print('Installed: ' .. path)
end

print('Installing Arcade OS...')

'@

$sb = New-Object System.Text.StringBuilder
$null = $sb.Append($header)

$root = (Get-Location).Path
$files = Get-ChildItem -Recurse -Filter "*.lua" -File |
    Where-Object { $_.FullName -ne (Join-Path $root "install.lua") -and $_.FullName -ne (Join-Path $root "bundle.ps1") } |
    Sort-Object FullName

foreach ($file in $files) {
    $content = Get-Content -Path $file.FullName -Raw -Encoding UTF8

    $relativePath = $file.FullName.Substring($root.Length).TrimStart('\','/')
    $relativePath = $relativePath -replace "\\", "/"
    
    # Determine appropriate delimiter
    $level = 0
    $open = "[" + "=" * $level + "["
    $close = "]" + "=" * $level + "]"
    
    while ($content.Contains($close)) {
        $level++
        $open = "[" + "=" * $level + "["
        $close = "]" + "=" * $level + "]"
    }
    
    $luaBlock = "writeFile('$relativePath', $open`n$content`n$close)" + "`n`n"
    $null = $sb.Append($luaBlock)
}

$footer = @'

-- Optional: set default game for this machine
local input = require('input')

local function readExistingArcadeConfig()
    if not fs.exists('.arcade_config') then return nil end
    local f = fs.open('.arcade_config', 'r')
    if not f then return nil end
    local cmd = (f.readAll() or '')
    f.close()
    cmd = cmd:gsub('%s+', '')
    if cmd == '' then return nil end
    return cmd
end

local function writeArcadeConfig(cmd)
    local f = fs.open('.arcade_config', 'w')
    f.write(cmd)
    f.close()
end

local function deleteArcadeConfig()
    if fs.exists('.arcade_config') then fs.delete('.arcade_config') end
end

local function configureDefaultGame()
    local options = {
        { name = 'Arcade Menu', cmd = 'menu' },
        { name = "Can't Stop (Free)", cmd = 'cant_stop' },
        { name = 'Horse Race', cmd = 'race' },
        { name = 'Super Slots', cmd = 'slots' },
        { name = 'Blackjack', cmd = 'blackjack' },
        { name = 'Baccarat', cmd = 'baccarat' },
        { name = 'RPS Rogue', cmd = 'rps_rogue' },
        { name = 'Roulette Watch', cmd = 'screensavers/roulette' },
        { name = 'Exchange', cmd = 'exchange' },
        { name = 'Cashier System', cmd = 'cashier' },
        { name = 'Update Arcade', cmd = 'update' },
        { name = 'Keep Current / Skip', cmd = nil }
    }

    local selected = 1
    local existing = readExistingArcadeConfig()

    -- Find existing option index
    for i, opt in ipairs(options) do
        if opt.cmd == existing then
            selected = i
            break
        end
    end

    local w, h = term.getSize()

    local function drawMenu()
        term.setBackgroundColor(colors.black)
        term.clear()
        term.setTextColor(colors.yellow)
        term.setCursorPos(1, 1)
        print('DEFAULT GAME CONFIG')
        term.setTextColor(colors.gray)
        print('Current: ' .. tostring(existing or '<none>'))
        print('')
        term.setTextColor(colors.white)
        print('[L] Up  [C] Select  [R] Down')
        print('')

        for i, opt in ipairs(options) do
            term.setCursorPos(1, 5 + i)
            if i == selected then
                term.setTextColor(colors.lime)
                term.write('> ' .. opt.name)
            else
                term.setTextColor(colors.white)
                term.write('  ' .. opt.name)
            end
        end

        term.setTextColor(colors.gray)
        term.setCursorPos(1, h)
        term.write('Kiosk mode active unless admin.key disk inserted')
    end

    drawMenu()

    while true do
        local event, p1 = os.pullEvent()
        local button = input.getButton(event, p1)

        if button == 'LEFT' then
            selected = selected - 1
            if selected < 1 then selected = #options end
            drawMenu()
        elseif button == 'RIGHT' then
            selected = selected + 1
            if selected > #options then selected = 1 end
            drawMenu()
        elseif button == 'CENTER' then
            local choice = options[selected]
            if choice.cmd == nil then
                -- Keep current / skip
                return
            end
            writeArcadeConfig(choice.cmd)
            term.setTextColor(colors.lime)
            print('')
            print('Set default to: ' .. choice.cmd)
            sleep(1)
            return
        end

        -- Also allow keyboard for convenience
        if event == 'key' then
            local name = keys.getName(p1)
            if name == 'up' then
                selected = selected - 1
                if selected < 1 then selected = #options end
                drawMenu()
            elseif name == 'down' then
                selected = selected + 1
                if selected > #options then selected = 1 end
                drawMenu()
            elseif name == 'enter' then
                local choice = options[selected]
                if choice.cmd == nil then
                    return
                end
                writeArcadeConfig(choice.cmd)
                term.setTextColor(colors.lime)
                print('')
                print('Set default to: ' .. choice.cmd)
                sleep(1)
                return
            end
        end
    end
end

print('Installation Complete!')
sleep(1)
configureDefaultGame()
print('')
print('Rebooting in 2 seconds...')
sleep(2)
os.reboot()
'@

$null = $sb.Append($footer)

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($outputFile, $sb.ToString(), $utf8NoBom)

Write-Host "Build complete: $outputFile"
