#!/usr/bin/env python3
"""Write wordle/guesses.lua, the words Daily Wordle accepts as guesses: the five-letter words
of Webster's Second (/usr/share/dict/web2, public domain), plurals of its four-letter words
(web2 has no inflected forms), and the modern and Minecraft words in EXTRA."""
from pathlib import Path
import re
here = Path(__file__).resolve().parents[1]
EXTRA = '''EMAIL PIXEL EMOJI NERFS NOOBS GAMER MODEM VIDEO RADIO LASER ROBOT TURBO
 SPAWN SCULK ALLAY GHAST LAPIS ENDER BIOME OTHER THEIR THERE WHERE WHICH
 BUILT MINED CRAFT GRIEF LOOTS RAIDS'''.split()
words = set()
dict_words = [w.strip() for w in open('/usr/share/dict/web2')]
for w in dict_words:
    if not re.fullmatch('[a-z]+', w): continue
    if len(w) == 5: words.add(w.upper())
    elif len(w) == 4 and not w.endswith('s'): words.add(w.upper() + 'S')
words |= set(EXTRA)
words |= set(re.findall(r"'([A-Z]{5})'", (here / 'words.lua').read_text()))
text = ''.join(sorted(words))
(here / 'guesses.lua').write_text('-- Generated by wordle/tools/guesses.py. Accepted guesses, five letters each, run together.\nreturn \'' + text + "'\n")
print(len(words), 'words', len(text) // 1024, 'KiB')
