-- Generated by tools/calibrate.lua, seeds 1..100000. Total returns include stake.
return {version='sim-1-calibration-100000-v1',simulation=1,samples=100000,wins={38045,26209,35746},meanSeconds=42.333199103433,
 payouts={{['5']=11,['10']=23,['20']=47},{['5']=17,['10']=34,['20']=68},{['5']=12,['10']=25,['20']=50}}}
